apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uqjpbim12-java-quarkus 
  janus-idp.io/tekton: uqjpbim12-java-quarkus
  backstage.io/kubernetes-id: uqjpbim12-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uqjpbim12-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml